version: 2.1 

 

jobs: 

  build-and-test:  

    machine: 

      image: mcr.microsoft.com/windows/servercore:ltsc2019 

        

    steps: 

      - checkout 

      - run: make deps 

      - run: make test       

workflows: 

  basic:  

    jobs: 

      - build-and-test

 